name: Experiment with google federated identity pull

on:
  - push

env:
# WORKLOAD_IDENTITY_PROVIDER: projects/96495653362/locations/global/workloadIdentityPools/ccreate-cicd-identity-pool/providers/github
  WORKLOAD_IDENTITY_PROVIDER: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/ccreate-cicd-identity-pool/providers/github
  SERVICE_ACCOUNT: artifact-registry-service@channel-rescue.iam.gserviceaccount.com
  DOCKER_IMAGE_PATH: europe-west2-docker.pkg.dev/channel-rescue/listener-services/ais-listener
  AUDIENCE: projects/channel-rescue/locations/global/workloadIdentityPools/ccreate-cicd-identity-pool/providers/github

jobs:
  authenticate:
    runs-on: ubuntu-latest
    permissions: 
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate GCloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - id: 'setup-gcloud'
        name: 'Setup the Google Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - id: 'auth_docker'
        name: 'Authenticate Docker repo'
        run: |- 
          echo "Authenticated as ${{ env.SERVICE_ACCOUNT }},\n with identity provider ${{ env.WORKLOAD_IDENTITY_PROVIDER }}"
          gcloud auth list --format=json
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://europe-west2-docker.pkg.dev
          gcloud auth print-access-token --audience=${{ env.WORKLOAD_IDENTITY_PROVIDER }} | docker login -u oauth2accesstoken --password-stdin https://europe-west2-docker.pkg.dev/channel-rescue


      - id: 'build-node'
        name: 'Build the docker image'
        uses: 'actions/setup-node@v2'
        with: 
          node-version: 21.6.0

      - id: 'setup'
        name: 'Install dependencies'
        run: npm ci

      - id: 'test'
        name: 'Run tests'
        run: npm test

      - id: 'build-docker'
        name: 'Build Docker Image'
        run: docker build -t europe-west2-docker.pkg.dev/channel-rescue/listener-services/ais-listener:latest .
# run: docker build -t ${{ env.DOCKER_IMAGE_PATH }}:latest -t ${{ env.DOCKER_IMAGE_PATH }}:${{ github.sha }} .


      - id: 'push'
        name: 'Push to Artifact Registry'
        run: |- 
          # gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://europe-west2-docker.pkg.dev
          docker push europe-west2-docker.pkg.dev/channel-rescue/listener-services/ais-listener:latest
          # docker push europe-west2-docker.pkg.dev/channel-rescue/listener-services/ais-listener --all-tags


          #       - id: 'deploy'
          #         uses: 'google-github-actions/deploy-cloudrun@v2'
          #         with:
          #           service: 'ais-listener'
          #           image: 'gcr.io/cloudrun/hello'

