name: Experiment with google federated identity pull

on:
  - push

env:
  WORKLOAD_IDENTITY_PROVIDER: 'projects/96495653362/locations/global/workloadIdentityPools/ccreate-cicd-identity-pool/providers/github'

jobs:
  authenticate:
    runs-on: ubuntu-latest
    permissions: 
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate GCloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: "$WORKLOAD_IDENTITY_PROVIDER"
          # workload_identity_provider: 'projects/96495653362/locations/global/workloadIdentityPools/ccreate-cicd-identity-pool/providers/github'
          service_account: 'artifact-registry-service@channel-rescue.iam.gserviceaccount.com'

      - id: 'setup-gcloud'
        name: 'Setup the Google Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - id: 'build-node'
        name: 'Build the docker image'
        uses: 'actions/setup-node@v2'
        with: 
          node-version: 21.6.0

      - id: 'setup'
        name: 'Install dependencies'
        run: npm ci

      - id: 'test'
        name: 'Run tests'
        run: npm test

      - id: 'build-docker'
        name: 'Build Docker Image'
          # run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}:$GITHUB_SHA .
        run: docker build -t europe-west2-docker.pkg.dev/channel-rescue/listener-services/ais-listener:latest .


      - id: 'push'
        name: 'Push to Artifact Registry'
        run: |- 
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://europe-west2-docker.pkg.dev
          docker push europe-west2-docker.pkg.dev/channel-rescue/listener-services/ais-listener:latest
          # run: docker push europe-west2-docker.pkg.dev/channel-rescue/listener-services/ais-listener:latest
