name: Experiment with google federated identity pull

on:
  - push

jobs:
  authenticate:
    runs-on: ubuntu-latest
    permissions: 
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate GCloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/96495653362/locations/global/workloadIdentityPools/ccreate-cicd-identity-pool/providers/github'
          service_account: 'artifact-registry-service@channel-rescue.iam.gserviceaccount.com'
