name: "Build and deploy"

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
  WORKLOAD_IDENTITY_PROVIDER: projects/${{secrets.GCP_PROJECT_NUMBER}}/locations/global/workloadIdentityPools/${{secrets.GCP_WORKLOAD_IDENTITY_POOL}}/providers/github
  DOCKER_REGISTRY: https://europe-west2-docker.pkg.dev

on:
  - push

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          token_format: 'access_token'
          export_environment_variables: true

      - name: Build and push docker
        run: |
          DOCKER_IMAGE="https://europe-west2-docker.pkg.dev/channel-rescue/listener-services/ais-listener"
          echo ${{ steps.auth.outputs.access_token }} | docker login -u oauth2accesstoken --password-stdin ${{ env.DOCKER_REGISTRY }}
          docker build -t ${DOCKER_IMAGE}:latest .
          docker push ${DOCKER_IMAGE}:latest
