name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.PROJECT_ID }}/my-node-app .
          docker push gcr.io/${{ secrets.PROJECT_ID }}/my-node-app

      # Add steps to deploy the Docker image to Cloud Run or any other Google Cloud service

